language: cpp
os:
- linux
sudo: required
dist: trusty

before_install:
  - sudo apt-get install libssl-dev
  - sh scripts/install-libprogbase.sh

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files
  

  
script:
  - qmake lab8.pro #we gonna compile for Unit test first
  - make
  - ./lab8 #run unit test


