sudo: required
language: cpp
os:
  - linux
compiler: 
  - g++	

before_install:
  - sudo apt-get install libjansson4 libjansson-dev
  - sudo apt-get install libssl-dev
  - sh scripts/install-libprogbase.sh

script: 
  - cmake . 
  - make
  - make json
