language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq—ñ
    - sudo apt-get install -qq qtbase5-dev
    - sudo apt-get install -qq qtdeclarative5-dev
    - sudo apt-get install -qq libqt5webkit5-dev
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
    - make lav8.pro
